### ISSUE TITLE
Cargo.lock is present in the repository.

### ISSUE THREAD

**Issue by f24816** [JonasKruckenberg/tauri-astro-template#16]
Cargo.lock should not be pushed to GitHub, you should have an exception for it in the .gitignore file and removed from git so it doesn't remain there.

**Comment by JonasKruckenberg** [comment]
Actually very unsure about this, the general recommendation for apps (end products) is to commit the lock file, since it provides build stability that's especially important rn while it uses the Tauri alpha version. 
But I can also see the argument that as a template it might be more like a library? not sure

**Comment by simkimsia** [comment]
keep it in, but do make sure that there's a full set of instructions for new users esp those new to astro and tauri. see #21  for details

**Comment by JonasKruckenberg** [comment]
deleted the lockfiles as well as providing some getting started instructions
